function returnDesc(filename) {
    let obj = {
        "PPI_lipid_metabolism_341_FirstOrder_high_confidence_StringDB": `This is the first order PPI network of lipid metabolism genes shared by Hiral. For generating this network, first direct neighbours of lipid metabolism genes are searched genes with “experiment” evidence and high confidence interaction score (0.7) in String database which resulted in 1044 genes. PPI network of these 1044 genes is created using StringDB using high interaction score (0.7).
            <br>Number of genes in the network = 1043
            <br>Number of interactions in the network = 8810`,

        "PPI_zero_order_lipid_metabolism_341": `This is zero order PPI network of lipid metabolism genes shared by Hiral generated by String database where low confidence interaction cut-off (0.15) is used.
            <br>Number of genes in the network = 300
            <br>Number of interactions in the network = 803`,
        "FunPPI_first_order_lipid_metabolism_341": `This is first order Functional PPI network of lipid metabolism with 341 genes using medium confidence
            <br>Number of genes in the network = 1544
            <br>Number of interactions in the network = 34503`,

        "PPI_first_order_lipid_metabolism_341": `This is first order PPI network of lipid metabolism with 341 genes using medium confidence
            <br>Number of genes in the network = 1544
            <br>Number of interactions in the network = 9817`,

        "PPI_first_order_laurens_list": `This is first order PPI network made from the gene list given by Lauren, using medium confidence
            <br>Number of genes in the network = 1659
            <br>Number of interactions in the network = 15017`,

        "FunPPI_first_order_laurens_list": `This is first order Functional PPI network made from the gene list given by Lauren, using medium confidence
            <br>Number of genes in the network = 1659
            <br>Number of interactions in the network = 43286`,


    }

    return obj[filename];
}